# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: searchall

on:
  push:
    branches: [ "main3.5.6" ]
  pull_request:
    branches: [ "main3.5.6" ]

      
jobs:

  build-armv7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: arm
            goarm: 7
            goos: linux
          
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install dependencies
      run: go get .

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }} 
        GOARM: ${{ matrix.goarm }} 
      run: go build -v ./...

    # - name: Test
    #   env:
    #     GOOS: ${{ matrix.goos }}
    #     GOARCH: ${{ matrix.goarch }} 
    #     GOARM: ${{ matrix.goarm }} 
      # run: go test -v ./...
